### PR TITLE
highlighting not dehighlighting hovered hyperlinks

### PR DESCRIPTION
**Pull request by rainwoodman**

### CODE REVIEW

**Comment by kbarbary** [comment]
Thanks!

**Comment by kbarbary** [comment]
oh, except that the relevant css is `next/assets/css/main.css`, not `assets/css/main.css`... so this change won't have the desired effect.

**Comment by rainwoodman** [comment]
Good to know. I'll do another PR.

**Comment by rainwoodman** [comment]
If those files are not useful, why still keeping them? Maybe rename the folder to unused-assets? or assets-template (if they serve as templates for next years).

**Comment by kbarbary** [comment]
The `next` directory has been holding a draft of the new site without it being "live" (though anyone who knows the link can access it obviously). I plan to move everything in `next` to the root sometime today, and start advertising the site tomorrow. The stuff currently in root is a throwaway site.

**Pull request merged**
